name = 'pcap_ada'
description = 'An Ada binding for pcap'
version = '1.0.0-dev'

authors = ['John Serock']
maintainers = ['John Serock <john.serock@gmail.com>']
maintainers-logins = ['serock']
licenses = 'BSD-3-Clause'
website = 'https://github.com/serock/pcap-ada'
tags = ['pcap', 'binding']

available."case(os)".freebsd."case(word-size)".bits-64 = true
available."case(os)".freebsd."case(word-size)".bits-32 = false
available."case(os)".linux."case(word-size)".bits-64 = true
available."case(os)".linux."case(word-size)".bits-32 = true
available."case(os)".openbsd."case(word-size)".bits-64 = true
available."case(os)".openbsd."case(word-size)".bits-32 = false
available."case(os)".windows."case(word-size)".bits-64 = true
available."case(os)".windows."case(word-size)".bits-32 = false
available."case(os)"."..." = false

[[depends-on]]
[depends-on."case(os)".windows]
npcap_sdk = '^1.0'

[configuration]
generate_ada = false
generate_c = false
